apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: managed-openshift-clusters-gitops
  namespace: policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: "In"
        values:
        - OpenShift
      - key: local-cluster
        operator: "NotIn"
        values:
        - "true"